#!/usr/bin/env bash
# Generates a compressed archive of a MySQL dump
# usage: ./5-mysql_backup [password of root user].
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
