#!/usr/bin/env bash
# Display the listening ports(ports in use)
# we run the netstat program with options;
# l: specifies listening ports
# p: displays the process ids of each program listed
netstat -lp
