#!/usr/bin/env bash
# Display the sentence "To infinity and beyond"
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command
# Displays Y U no love me?! when receiving a SIGINT signal
# Creates the file /var/run/myscript.pid
# Deletes the file /var/run/myscript.pid nd terminates itself
# when receiving a SIGQUIT or SIGTERM signal

echo "$$"> /var/run/myscript.pid
while true; do
    echo "To infinity and beyond";
    sleep 2;
#    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm /var/run/myscript.pid' SIGQUIT
    trap 'echo "I hate the kill command" && rm /var/run/myscript.pid && exit' SIGTERM
done

