#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
LMT=10
i=0
while [ $i -lt $LMT  ]; do
    i=$((i + 1))
    if [ $i -eq 4 ]; then
        echo "bad luck";
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School";
    fi
done

