#!/usr/bin/env bash
# 7-clock - script to  print hour from 0 to 12
# and minute from  1 to 59
# Simon Tagbor <simontagbor360@gmail.com>

hour=0


while [ $hour -le 12 ]; do
    echo "Hour: $hour";
    minute=1
    while [ $minute -le 59 ]; do
        echo "$minute";
        ((minute++))
    done
    ((hour++))
done
